name = "web"
account_id = "2575000dd90a08dbbeb2b8cca2e64775" # scraper.workers.dev
type = "webpack"
workers_dev = true
kv_namespaces = [
  { binding = "vault", id = "d977b0d55a9848559b183baf0417f2d2" }
]